version: "3.9"
services:
  database:
    restart: always
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    user: root
    ports:
      - "1433:1433"
    volumes:
      - database-data:/var/opt/mssql/data
    environment:
      SA_PASSWORD: "S3cur3P@ssW0rd!"
      ACCEPT_EULA: "Y"

volumes:
  database-data: