

name: Web Client - Deploy Image to acr

on:
  push:
    branches:
      - main
    paths:
      - SolenLmsApp/WebClient/**
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: solenlmswebclient
  IMAGE_NAME: webclient 
  DOCKERFILE_PATH: 'SolenLmsApp/WebClient/Server/Dockerfile'  
  
jobs:
   deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          tags: |
            ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'stage'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_WEBCLIENT_STAGE }}
          images: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
